### PR TITLE
Support Visual Studio 2019

### PR DESCRIPTION
**Pull request by jupeter**

### CODE REVIEW

**Comment by jupeter** [comment]
Hi @Igorbek,
I added support for Visual Studio 2019. 
Would it be possible for you to merge it and release and release new NuGet package version?
Appreciated for you answer.

**Comment by jupeter** [comment]
Hi @Igorbek . Any news in this are?

**Comment by Igorbek** [comment]
Ah, sorry, I didn't notice there was a PR. Thank you for the contribution @jupeter! Let me try it out.

**Comment by jupeter** [comment]
Hi @Igorbek 
Thank you. If I can help you on it, please let me know. 
It would be great for me if new version can appear soon. 
Thank you!

**Comment by Igorbek** [comment]
@jupeter thank you! I think I'll re-organize folders a little bit to include a fallback inclusion of the projects to simplify upgrading in the future.

**Pull request merged**
