### PR TITLE
Updating CodeContracts to 1.9.10714.2

### PR DESCRIPTION
**Pull request by ericmaino**
- Updates the version of code contracts which supports C# 6.0 features
- Includes Languages folder which is required for compilation if code
  contracts have not been installed on the machines.
- Includes MSBuild v14.0 targets

### CODE REVIEW

**Comment by Igorbek** [comment]
Thanks a lot for contribution. Sorry for being late in review.
Could you please remove `Contracts/Languages/*` files. They are for IDE and not needed for MSBuild at all.

**Comment by ericmaino** [comment]
Some of them are required for MSBuild in v14. I only added them because of build breaks looking for them. Yes I added all of them so we could reduce that number but there are definitely some that are required.

**Comment by ericmaino** [comment]
Here is the build failure when Languages are not present

"C:\src\Athens\Athens.Contracts\Athens.Contracts.csproj" (rebuild target) (1) ->
(ContractDeclarativeAssemblyCS target) ->
  CSC : error CS2001: Source file 'C:\src\Athens\packages\Athens.CodeContracts.1.0.0.2\build\Contracts\Languages\CSharp
\ContractDeclarativeAssemblyAttribute.cs' could not be found. [C:\src\Athens\Athens.Contracts\Athens.Contracts.csproj]

**Comment by Igorbek** [comment]
Oh, I see. There're some *.cs files. Could you remove `*.snippet`?

**Comment by Igorbek** [comment]
:cake:  Thank you!

**Comment by ericmaino** [comment]
My pleasure!

**Pull request merged**
